name: publish

on:
  push:
    branches:    
      - master

jobs:
  publish_npm:
    name: publish npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release -d